In [1]:
import requests
import pandas as pd
from pandas import DataFrame
import numpy as np
from itertools import chain
import matplotlib.pyplot as plt
import seaborn as sns
import spotipy
sp = spotipy.Spotify()
from spotipy.oauth2 import SpotifyClientCredentials

%matplotlib inline

# FULL DATAFRAME

In [2]:
df_1972=pd.read_csv('../data/final_1972_df')
df_1982=pd.read_csv('../data/final_1982_df')
df_1992=pd.read_csv('../data/final_1992_df')
df_2002=pd.read_csv('../data/final_2002_df')
df_2012=pd.read_csv('../data/final_2012_df')
df_2022=pd.read_csv('../data/final_2022_df')

In [3]:
FULL_DF=pd.concat([df_1972,df_1982,df_1992,df_2002,df_2012,df_2022]).reset_index()
FULL_DF= FULL_DF.drop(columns=['level_0','Unnamed: 0'])
FULL_DF

,index,artist_name,year,track_name,primary_genre,sub_genre_1,sub_genre_2,danceability,energy,key,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,track_uri,duration_ms,time_signature
0,0,Roberta Flack,1972,The First Time Ever I Saw Your Face,adult standards,classic soul,disco,0.311,0.0264,0,...,1,0.0370,0.7310,0.002050,0.1560,0.139,120.653,0SxFyA4FqmEQqZVuAlg8lf,260666,4
1,1,Gilbert O'Sullivan,1972,Alone Again (Naturally),adult standards,brill building pop,bubblegum pop,0.558,0.4640,8,...,0,0.0354,0.5830,0.000133,0.1590,0.558,171.762,6vuEG9sZtC4W2zT64f7zLF,217729,4
2,2,Don McLean,1972,American Pie,adult standards,classic rock,folk,0.531,0.4810,4,...,0,0.0600,0.6990,0.000000,0.0842,0.491,138.450,1fDsrQ23eTAVFElUMaf38X,516893,4
3,3,Harry Nilsson,1972,Without You,art rock,brill building pop,classic rock,0.381,0.1860,4,...,1,0.0290,0.6130,0.000003,0.0694,0.142,65.058,6MrILERJLA3Jcq0E9poZsp,201000,4
4,4,Sammy Davis Jr.,1972,The Candy Man,adult standards,easy listening,lounge,0.634,0.5600,0,...,1,0.0370,0.6810,0.000000,0.3670,0.880,131.641,5X3XrHlCFVGqNKpGp85xVC,188227,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,95,Stephen Sanchez,2022,Until I Found You,gen z singer-songwriter,NaN,NaN,0.539,0.5080,10,...,1,0.0288,0.7270,0.000000,0.1740,0.227,101.358,0T5iIrXA4p5GsubkhuBIKV,177720,3
555,96,Bad Bunny,2022,Un Ratito,latin,reggaeton,trap latino,0.787,0.5460,0,...,0,0.0532,0.3050,0.000046,0.1220,0.222,93.050,5CzixCxDkRXX9mScCmah8O,176936,4
556,97,Jake Owen,2022,Best Thing Since Backroads,contemporary country,country,country road,0.512,0.8410,7,...,1,0.0309,0.0424,0.000257,0.1130,0.330,156.077,0R1REdJZIDy7IS3DybdBce,187433,4
557,98,Bad Bunny,2022,La Corriente,latin,reggaeton,trap latino,0.663,0.7860,11,...,0,0.1950,0.2290,0.000000,0.2190,0.579,196.120,1797zYiX4cKosMH836X9Gt,198367,4
558,99,Bizarrap,2022,"Quevedo: Bzrp Music Sessions, Vol. 52",argentine hip hop,pop venezolano,trap argentino,0.621,0.7820,2,...,1,0.0440,0.0125,0.033000,0.2300,0.550,128.033,2tTmW7RDtMQtBk7m2rYeSw,198938,4

# PERCENT TIME SIGNATURE IN 4/4

In [4]:
p_time_sig_1972=pd.read_csv('../data/percent_time_sig_1972')
p_time_sig_1982=pd.read_csv('../data/percent_time_sig_1982')
p_time_sig_1992=pd.read_csv('../data/percent_time_sig_1992')
p_time_sig_2002=pd.read_csv('../data/percent_time_sig_2002')
p_time_sig_2012=pd.read_csv('../data/percent_time_sig_2012')
p_time_sig_2022=pd.read_csv('../data/percent_time_sig_2022')

In [5]:
#time_sig=pd.merge([p_time_sig_1972,p_time_sig_1982,p_time_sig_1992,p_time_sig_2002,p_time_sig_2012,p_time_sig_2022])
time_sig=p_time_sig_1972.merge(p_time_sig_1982, how='left', on='index')
time_sig=time_sig.merge(p_time_sig_1992, how='left', on='index')
time_sig=time_sig.merge(p_time_sig_2002, how='left', on='index')
time_sig=time_sig.merge(p_time_sig_2012, how='left', on='index')
time_sig=time_sig.merge(p_time_sig_2022, how='left', on='index')
time_sig=time_sig.drop(columns=['Unnamed: 0_x','Unnamed: 0_y'])
time_sig

C:\Users\vital\AppData\Local\Temp\ipykernel_19916\2067169621.py:4: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Unnamed: 0_x'} in the result is deprecated and will raise a MergeError in a future version.
  time_sig=time_sig.merge(p_time_sig_2002, how='left', on='index')
C:\Users\vital\AppData\Local\Temp\ipykernel_19916\2067169621.py:6: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Unnamed: 0_x'} in the result is deprecated and will raise a MergeError in a future version.
  time_sig=time_sig.merge(p_time_sig_2022, how='left', on='index')

,index,time_sig_72,time_sig_82,time_sig_92,time_sig_02,time_sig_12,time_sig_22
0,0,92.857143,96.969697,97.0,97.802198,97.183099,91.0

# MOST POPULAR GENRES

In [6]:
p_genres_1972=pd.read_csv('../data/genre_df_1972')
p_genres_1982=pd.read_csv('../data/genre_1982_df')
p_genres_1992=pd.read_csv('../data/genre_df_1992')
p_genres_2002=pd.read_csv('../data/genre_df_2002')
p_genres_2012=pd.read_csv('../data/genre_df_2012')
p_genres_2022=pd.read_csv('../data/genre_df_2022')

In [7]:
genres_df=pd.concat([p_genres_1972,p_genres_1982,p_genres_1992,p_genres_2002,p_genres_2012,p_genres_2022]).reset_index()
genres_df= genres_df.drop(columns=['level_0','Unnamed: 0'])
genres_df

,index,year,primary_genre,p_gen_count,pg_count,sub_genre_1,sg1_count,s1_count,sub_genre_2,sg2_count,s2_count
0,0,1972,adult standards,17,26,brill building pop,11.0,35.0,classic rock,11.0,25.0
1,1,1972,classic soul,17,26,classic rock,8.0,35.0,soul,6.0,25.0
2,2,1972,album rock,14,26,classic soul,8.0,35.0,funk,6.0,25.0
3,3,1972,bubblegum pop,6,26,art rock,8.0,35.0,bubblegum pop,5.0,25.0
4,4,1972,funk,4,26,funk,6.0,35.0,country rock,5.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...
85,10,2022,memphis hip hop,1,30,melodic rap,2.0,29.0,trap argentino,1.0,25.0
86,11,2022,minnesota hip hop,1,30,mellow gold,1.0,29.0,trap,1.0,25.0
87,12,2022,glam rock,1,30,pop venezolano,1.0,29.0,tennessee hip hop,1.0,25.0
88,13,2022,modern rock,1,30,piano rock,1.0,29.0,shiver pop,1.0,25.0
89,14,2022,gen z singer-songwriter,1,30,rock,1.0,29.0,reggaeton colombiano,1.0,25.0

# MOST POPULAR KEYS

In [8]:
p_keys_1972=pd.read_csv('../data/pop_key_1972')
p_keys_1982=pd.read_csv('../data/pop_key_1982')
p_keys_1992=pd.read_csv('../data/pop_key_1992')
p_keys_2002=pd.read_csv('../data/pop_key_2002')
p_keys_2012=pd.read_csv('../data/pop_key_2012')
p_keys_2022=pd.read_csv('../data/pop_key_2022')

In [9]:
pop_keys=p_keys_1972.merge(p_keys_1982, how='left', on='index')
pop_keys=pop_keys.merge(p_keys_1992, how='left', on='index')
pop_keys=pop_keys.merge(p_keys_2002, how='left', on='index')
pop_keys=pop_keys.merge(p_keys_2012, how='left', on='index')
pop_keys=pop_keys.merge(p_keys_2022, how='left', on='index')
pop_keys=pop_keys.drop(columns=['Unnamed: 0_x','Unnamed: 0_y'])
pop_keys

C:\Users\vital\AppData\Local\Temp\ipykernel_19916\842046623.py:3: FutureWarning: Passing 'suffixes' which cause duplicate columns {'year_x', 'alph_key_x', 'Unnamed: 0_x', 'count_x'} in the result is deprecated and will raise a MergeError in a future version.
  pop_keys=pop_keys.merge(p_keys_2002, how='left', on='index')
C:\Users\vital\AppData\Local\Temp\ipykernel_19916\842046623.py:5: FutureWarning: Passing 'suffixes' which cause duplicate columns {'year_x', 'alph_key_x', 'Unnamed: 0_x', 'count_x'} in the result is deprecated and will raise a MergeError in a future version.
  pop_keys=pop_keys.merge(p_keys_2022, how='left', on='index')

,index,alph_key_x,count_x,year_x,alph_key_y,count_y,year_y,alph_key_x,count_x,year_x,alph_key_y,count_y,year_y,alph_key_x,count_x,year_x,alph_key_y,count_y,year_y
0,0,CMajor,11,1972,EMajor,12,1982,C#Major,13,1992,DMajor,13,2002,CMajor,9,2012,C#Major,18,2022
1,1,AMajor,10,1972,DMajor,11,1982,Bminor,9,1992,C#Major,8,2002,C#minor,7,2012,DMajor,8,2022
2,2,GMajor,8,1972,CMajor,10,1982,Fminor,8,1992,G#Major,8,2002,GMajor,6,2012,GMajor,8,2022
3,3,FMajor,8,1972,AMajor,8,1982,GMajor,7,1992,F#Major,6,2002,Cminor,5,2012,G#Major,6,2022
4,4,Eminor,8,1972,GMajor,6,1982,CMajor,7,1992,GMajor,6,2002,Gminor,4,2012,A#Major,6,2022
5,5,A#Major,7,1972,G#Major,6,1982,EMajor,6,1992,Bminor,5,2002,Bminor,4,2012,AMajor,6,2022
6,6,EMajor,7,1972,FMajor,6,1982,AMajor,6,1992,C#minor,5,2002,Fminor,4,2012,Bminor,5,2022
7,7,DMajor,7,1972,C#Major,5,1982,FMajor,5,1992,CMajor,5,2002,FMajor,4,2012,F#Major,5,2022
8,8,Bminor,6,1972,Gminor,4,1982,A#Major,4,1992,BMajor,4,2002,EMajor,3,2012,Fminor,5,2022
9,9,C#Major,5,1972,Aminor,4,1982,G#Major,4,1992,Aminor,4,2002,G#Major,3,2012,FMajor,4,2022
10,10,C#minor,3,1972,BMajor,4,1982,F#minor,4,1992,Fminor,4,2002,A#Major,3,2012,Eminor,4,2022
11,11,BMajor,3,1972,Dminor,4,1982,F#Major,4,1992,D#minor,3,2002,C#Major,3,2012,CMajor,4,2022
12,12,G#Major,3,1972,Eminor,3,1982,Gminor,4,1992,EMajor,3,2002,AMajor,3,2012,A#minor,3,2022
13,13,D#Major,2,1972,D#Major,3,1982,A#minor,3,1992,Eminor,3,2002,DMajor,3,2012,D#minor,3,2022
14,14,Dminor,2,1972,Cminor,3,1982,Cminor,3,1992,A#minor,2,2002,F#Major,2,2012,BMajor,3,2022
15,15,Fminor,2,1972,Bminor,3,1982,DMajor,3,1992,Dminor,2,2002,D#Major,2,2012,G#minor,3,2022
16,16,G#minor,2,1972,C#minor,2,1982,Eminor,2,1992,AMajor,2,2002,Aminor,2,2012,EMajor,2,2022
17,17,Cminor,1,1972,A#Major,2,1982,D#Major,2,1992,F#minor,2,2002,Dminor,1,2012,C#minor,2,2022
18,18,F#minor,1,1972,A#minor,1,1982,Aminor,2,1992,G#minor,2,2002,A#minor,1,2012,Cminor,2,2022
19,19,Aminor,1,1972,F#Major,1,1982,Dminor,1,1992,A#Major,1,2002,Eminor,1,2012,F#minor,1,2022
20,20,Gminor,1,1972,Fminor,1,1982,C#minor,1,1992,FMajor,1,2002,G#minor,1,2012,D#Major,1,2022

# LIVENESS- DURATION

In [10]:
duration_live_1972=pd.read_csv('../data/duration_1972_df')
duration_live_1982=pd.read_csv('../data/duration_1982_df')
duration_live_1992=pd.read_csv('../data/duration_1992_df')
duration_live_2002=pd.read_csv('../data/duration_2002_df')
duration_live_2012=pd.read_csv('../data/duration_2012_df')
duration_live_2022=pd.read_csv('../data/duration_2022_df')

In [11]:
duration_live_df=pd.concat([duration_live_1972,duration_live_1982, duration_live_1992,duration_live_2002,duration_live_2012,duration_live_2022]).reset_index()
duration_live_df= duration_live_df.drop(columns=['level_0','Unnamed: 0'])
duration_live_df

,index,dur_avg,top10_dur_avg,top_song_dur,live_avg,top10_live_avg,top_song_live,year
0,0,3.566873,3.870887,4.344433,19.247449,15.027,15.60,1972
1,0,3.887549,3.871397,3.706667,19.211414,22.216,28.40,1982
2,0,4.625752,4.496427,5.818917,16.947200,13.168,6.73,1992
3,0,4.130386,3.813688,3.713333,16.655934,16.250,9.60,2002
4,0,3.724666,3.627405,4.081417,18.321408,13.424,9.89,2012
5,0,3.346545,3.422918,4.638033,18.431900,18.845,27.00,2022

# VALENCE- ACCOUSTINESS- SPEECHINESS

In [12]:
tone_1972=pd.read_csv('../data/tone1972_df')
tone_1982=pd.read_csv('../data/tone1982_df')
tone_1992=pd.read_csv('../data/tone1992_df')
tone_2002=pd.read_csv('../data/tone2002_df')
tone_2012=pd.read_csv('../data/tone2012_df')
tone_2022=pd.read_csv('../data/tone2022_df')

In [13]:
tone_df=pd.concat([tone_1972,tone_1982, tone_1992,tone_2002,tone_2012,tone_2022]).reset_index()
tone_df= tone_df.drop(columns=['level_0','Unnamed: 0'])
tone_df

,index,valence_avg,top10_valence_avg,top_song_valence,accoustic_avg,top10_accoustic_avg,top_song_accoustic,speechiness_avg,top10_speechiness_avg,top_song_speechiness,year
0,0,66.111224,55.70,13.9,43.850204,59.18000,73.1000,5.655306,59.18000,73.1000,1972
1,0,65.373434,77.76,85.7,27.162631,20.96400,13.0000,3.826465,20.96400,13.0000,1982
2,0,56.132600,55.32,55.0,17.750894,17.57211,3.4300,5.916300,17.57211,3.4300,1992
3,0,59.302308,58.31,55.8,15.853605,11.64646,0.0866,9.759560,11.64646,0.0866,2002
4,0,58.161972,68.94,74.8,11.095124,8.83800,54.8000,6.908028,8.83800,54.8000,2012
5,0,47.118600,58.97,85.3,17.228367,28.63500,5.7500,10.531400,28.63500,5.7500,2022

# ENERGY-DANCE_TEMPO

In [15]:
energy_1972=pd.read_csv('../data/energy_1972_df')
energy_1982=pd.read_csv('../data/energy_1982_df')
energy_1992=pd.read_csv('../data/energy_1992_df')
energy_2002=pd.read_csv('../data/energy_2002_df')
energy_2012=pd.read_csv('../data/energy_2012_df')
energy_2022=pd.read_csv('../data/energy_2022_df')

In [17]:
energy_df=pd.concat([energy_1972,energy_1982, energy_1992,energy_2002,energy_2012,energy_2022]).reset_index()
energy_df= energy_df.drop(columns=['level_0','Unnamed: 0'])
energy_df

,index,dance_avg,top10_dance_avg,top_song_dance,tempo_avg,top10_tempo_avg,top_song_tempo,energy_avg,top10_energy_avg,top_song_energy,year
0,0,57.580612,58.28,31.1,121.085510,106.3073,120.653,52.969796,37.934,2.64,1972
1,0,61.348485,71.29,82.9,124.600758,114.1552,123.878,58.280808,58.670,73.70,1982
2,0,63.704000,68.01,56.1,117.563190,113.4070,74.822,64.076000,57.000,57.90,1992
3,0,67.260440,62.42,54.5,120.270385,111.6727,85.974,68.670330,74.810,77.70,2002
4,0,65.640845,67.80,86.5,121.917056,128.4123,129.059,75.950704,73.550,52.10,2012
5,0,67.748000,71.15,68.7,121.120790,120.3919,114.941,65.522000,67.600,88.70,2022