# PERMISSIONS AUTHORIZATION

In [1]:
import requests
import pandas as pd
from pandas import DataFrame
import numpy as np
from itertools import chain
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
CLIENT_ID = 'c7d16c8600ab433ea5aede2202285c1e'
CLIENT_SECRET = '69b7f20b150845a1ae6427a66f14d780'

In [3]:
AUTH_URL = 'https://accounts.spotify.com/api/token'

# POST
auth_response = requests.post(AUTH_URL, {
    'grant_type': 'client_credentials',
    'client_id': CLIENT_ID,
    'client_secret': CLIENT_SECRET,
})

# convert the response to JSON
auth_response_data = auth_response.json()

# save the access token
access_token = auth_response_data['access_token']

In [4]:
#needs to be updated every hour
headers = {
    'Authorization': 'Bearer BQAlVnemLaeHsWsztFH5TMWJ8Bvmgzf175Kts23DSFDcMuYNgjxEtfpnViAJUCv06aviIGZ-vJEeTNk3-55cELa1DaQVFPQ9EXe4_pqykzBh1XQhd5a8nQnkeCL9OY--yBKYPSOSnG1V3Pt0D4ab-_PKqdPgzT9DQFTCjmG4IgvvyeUT7v1OlcsspKv1pJt11KI'.format(token=access_token)
}

# PULLING IN BILLBOARD 1982

In [6]:
import spotipy
sp = spotipy.Spotify()
from spotipy.oauth2 import SpotifyClientCredentials

In [7]:
#Authentication - without user
client_credentials_manager = SpotifyClientCredentials(client_id=CLIENT_ID, client_secret=CLIENT_SECRET)
sp = spotipy.Spotify(client_credentials_manager = client_credentials_manager)

In [8]:
playlist_link = "https://open.spotify.com/embed/playlist/1bk6tO6d5oes6n0vhACi5x?utm_source=generator"
playlist_URI = playlist_link.split("/")[-1].split("?")[0]
track_uris = [x["track"]["uri"] for x in sp.playlist_tracks(playlist_URI)["items"]]

In [9]:
    for track in sp.playlist_tracks(playlist_URI)["items"]:
        #URI
        track_uri = track["track"]["uri"]

        #Track name
        track_name = track["track"]["name"]

        #Main Artist
        artist_uri = track["track"]["artists"][0]["uri"]
        artist_info = sp.artist(artist_uri)

        #Name, popularity, genre
        artist_name = track["track"]["artists"][0]["name"]
        
        #artist_pop = artist_info["popularity"]
        artist_genres = artist_info["genres"]

        #Album
        album = track["track"]["album"]["name"]

        #Popularity of the track
        track_pop = track["track"]["popularity"]
        
        #Track Name
        track_name = track["track"]["name"]
        
        #Track URI
        track_uri = track["track"]["uri"]

# TRACK URI

In [10]:
def get_playlist_uri(playlist_link):
    return playlist_link.split("/")[-1].split("?")[0]


def get_tracks():
    tracks = []
    playlist_uri = get_playlist_uri(playlist_link)
    for track in sp.playlist_tracks(playlist_uri)["items"]:
        track_uri = track["track"]["uri"]
        track_name = track["track"]["name"]
        result = track_uri#, sp.audio_features(track_uri)
        tracks.append(result)

    return tracks


track_u = get_tracks()

In [11]:
t_uri=pd.DataFrame(track_u)
t_uri=t_uri.rename(columns={0:'track_uri'})
t_uri=t_uri['track_uri'].str.lstrip('spotify:track:')
t_uri=pd.DataFrame(t_uri)

# ARTIST NAME

In [12]:
def get_playlist_uri(playlist_link):
    return playlist_link.split("/")[-1].split("?")[0]


def get_tracks():
    tracks = []
    playlist_uri = get_playlist_uri(playlist_link)
    for track in sp.playlist_tracks(playlist_uri)["items"]:
        artist_name = track["track"]["artists"][0]["name"]
        result = artist_name
        tracks.append(result)

    return tracks


artist_name = get_tracks()

In [13]:
a_name=pd.DataFrame(artist_name).reset_index()
a_name=a_name.rename(columns={0:'artist_name'})
a_name['year']=1982

# TRACK NAME

In [14]:
def get_playlist_uri(playlist_link):
    return playlist_link.split("/")[-1].split("?")[0]


def get_tracks():
    tracks = []
    playlist_uri = get_playlist_uri(playlist_link)
    for track in sp.playlist_tracks(playlist_uri)["items"]:
        track_name = track["track"]["name"]
        result = track_name#, sp.audio_features(track_uri)
        tracks.append(result)

    return tracks


track_name = get_tracks()

In [15]:
t_name=pd.DataFrame(track_name).reset_index()
t_name=t_name.rename(columns={0:'track_name'})

# AUDIO FEATURES

In [16]:
def get_playlist_uri(playlist_link):
    return playlist_link.split("/")[-1].split("?")[0]


def get_tracks():
    tracks = []
    playlist_uri = get_playlist_uri(playlist_link)
    for track in sp.playlist_tracks(playlist_uri)["items"]:
        track_name = track["track"]["name"]
        track_uri = track["track"]["uri"]
        result = sp.audio_features(track_uri)[0]
        tracks.append(result)
        #result=pd.concat([sp.audio_features, tracks], axis=0)
    return tracks


audio = get_tracks()

audio

In [17]:
audio_fea=pd.DataFrame(audio).reset_index()
audio_fea=audio_fea.drop(columns=['type','uri','track_href','analysis_url'])
audio_fea=audio_fea.rename(columns={'id':'track_uri'})

# GENRES

In [18]:
def get_playlist_uri(playlist_link):
    return playlist_link.split("/")[-1].split("?")[0]


def get_tracks():
    tracks = []
    playlist_uri = get_playlist_uri(playlist_link)
    for track in sp.playlist_tracks(playlist_uri)["items"]:
        artist_uri = track["track"]["artists"][0]["uri"]
        artist_info = sp.artist(artist_uri)
        artist_genres = artist_info["genres"]
        result = artist_genres
        tracks.append(result)

    return tracks


track_genres = get_tracks()

In [19]:
genres=pd.DataFrame(track_genres)
genres=genres.rename(columns={0:'primary_genre',1:'sub_genre_1', 2:'sub_genre_2'})
genres= genres[['primary_genre','sub_genre_1','sub_genre_2']].reset_index()

In [20]:
final_1982_df=a_name.merge(t_name, how='left', on='index')
final_1982_df=final_1982_df.merge(genres, how='left', on='index')
final_1982_df=final_1982_df.merge(audio_fea, how='left', on='index')
final_1982_df.head(10)

,index,artist_name,year,track_name,primary_genre,sub_genre_1,sub_genre_2,danceability,energy,key,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,track_uri,duration_ms,time_signature
0,0,Olivia Newton-John,1982,Physical,adult standards,australian dance,bubblegum pop,0.829,0.737,4,...,0,0.0441,0.1300,0.000063,0.2840,0.857,123.878,3FuL7jThtUAjneBm6puQNk,222400,4
1,1,Survivor,1982,Eye of the Tiger,album rock,hard rock,rock,0.815,0.438,0,...,0,0.0346,0.2160,0.000466,0.0787,0.552,108.965,2HHtWyy5CgaQbC7XSoOb0e,243773,4
2,2,Joan Jett & the Blackhearts,1982,I Love Rock 'N Roll,glam punk,rock,None,0.535,0.716,4,...,1,0.0431,0.3260,0.000000,0.6590,0.901,94.379,2Cdvbe2G4hZsnhNMKyGrie,175173,4
3,3,Paul McCartney,1982,Ebony And Ivory,album rock,beatlesque,classic rock,0.639,0.458,4,...,1,0.0343,0.1520,0.000000,0.1680,0.805,80.692,1h3bcnnIm72UnemGIfm0iZ,220773,4
4,4,The J. Geils Band,1982,Centerfold,album rock,art rock,blues rock,0.653,0.677,0,...,1,0.0396,0.2490,0.000000,0.4030,0.888,114.370,1ynmMEK1fkyiZ6Z6F3ThEt,216533,4
5,5,The Human League,1982,Don't You Want Me,art rock,new romantic,new wave,0.734,0.742,9,...,0,0.0382,0.1750,0.000000,0.1340,0.957,117.652,7zhtLp2V3lNXdllknAqbKk,240533,4
6,6,John Mellencamp,1982,Jack & Diane,album rock,classic rock,country rock,0.811,0.410,9,...,1,0.0391,0.0365,0.000007,0.0799,0.626,103.965,43btz2xjMKpcmjkuRsvxyg,254493,4
7,7,John Mellencamp,1982,Hurts So Good,album rock,classic rock,country rock,0.785,0.737,9,...,1,0.0363,0.0420,0.000107,0.1080,0.971,125.447,67eX1ovaHyVPUinMHeUtIM,218960,4
8,8,Steve Miller Band,1982,Abracadabra,album rock,blues rock,classic rock,0.791,0.535,9,...,0,0.0355,0.0749,0.000002,0.1560,0.963,127.488,2E2ZVy2fxslpAUgbb4zu84,308373,4
9,9,Chicago,1982,Hard to Say I'm Sorry - 2009 Remaster,adult standards,album rock,classic rock,0.537,0.417,4,...,1,0.0273,0.6950,0.000002,0.1510,0.256,144.716,5nDSJO4909uNzMcZH3CggS,221827,4

In [21]:
modes=final_1982_df.groupby(['mode']).count()
modes

,index,artist_name,year,track_name,primary_genre,sub_genre_1,sub_genre_2,danceability,energy,key,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,track_uri,duration_ms,time_signature
mode,,,,,,,,,,,,,,,,,,,,
0,25,25,25,25,25,25,23,25,25,25,25,25,25,25,25,25,25,25,25,25
1,74,74,74,74,72,69,64,74,74,74,74,74,74,74,74,74,74,74,74,74

# TIME SIGNATURE PERCENTAGES

In [66]:
time_sig=final_1982_df[final_1982_df['time_signature']==4]
percent_time_sig_1982=time_sig['track_name'].count()/final_1982_df['track_name'].count() *100
percent_time_sig_1982

96.96969696969697

# GENRES

In [23]:
genres=final_1982_df[['year','primary_genre','sub_genre_1','sub_genre_2']]
genres['genre_count'] =1

C:\Users\vital\AppData\Local\Temp\ipykernel_34380\1057796131.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genres['genre_count'] =1

In [24]:
primary_g=genres[['year','primary_genre', 'genre_count']]
primary_g=primary_g.groupby(['year','primary_genre'])['genre_count'].sum()
primary_g=pd.DataFrame(primary_g).reset_index().sort_values(['genre_count'], ascending=False)
primary_g=primary_g.reset_index()
primary_g=primary_g.drop(columns=['index'])
primary_g=primary_g.reset_index()
primary_g['pg_count']= primary_g['primary_genre'].count()

In [25]:
sub_g_1=genres[['year','sub_genre_1', 'genre_count']]
sub_g_1=sub_g_1.groupby(['year','sub_genre_1'])['genre_count'].sum()
sub_g_1=pd.DataFrame(sub_g_1).reset_index().sort_values(['genre_count'], ascending=False)
sub_g_1=sub_g_1.reset_index()
sub_g_1=sub_g_1.drop(columns=['index'])
sub_g_1=sub_g_1.reset_index()
sub_g_1['s1_count']= sub_g_1['sub_genre_1'].count()

In [26]:
sub_g_2=genres[['year','sub_genre_2', 'genre_count']]
sub_g_2=sub_g_2.groupby(['year','sub_genre_2'])['genre_count'].sum()
sub_g_2=pd.DataFrame(sub_g_2).reset_index().sort_values(['genre_count'], ascending=False)
sub_g_2=sub_g_2.reset_index()
sub_g_2=sub_g_2.drop(columns=['index'])
sub_g_2=sub_g_2.reset_index()
sub_g_2['s2_count']= sub_g_2['sub_genre_2'].count()

In [27]:
genre_1982_df=primary_g.merge(sub_g_1, how='left', on='index')
genre_1982_df=genre_1982_df.merge(sub_g_2, how='left', on='index')
genre_1982_df=genre_1982_df.drop(columns=['year_y','year']).head(15)
genre_1982_df=genre_1982_df.rename(columns={'year_x':'year','genre_count_x':'p_gen_count','genre_count_y':'sg1_count','genre_count':'sg2_count'})
genre_1982_df

,index,year,primary_genre,p_gen_count,pg_count,sub_genre_1,sg1_count,s1_count,sub_genre_2,sg2_count,s2_count
0,0,1982,album rock,45,17,classic rock,20,34,classic rock,15,25
1,1,1982,adult standards,16,17,art rock,9,34,country rock,15,25
2,2,1982,disco,10,17,disco,6,34,mellow gold,10,25
3,3,1982,mellow gold,5,17,mellow gold,5,34,hard rock,5,25
4,4,1982,classic country pop,4,17,funk,5,34,new wave pop,4,25
5,5,1982,country,2,17,soft rock,4,34,girl group,4,25
6,6,1982,funk,2,17,bubblegum pop,3,34,soft rock,3,25
7,7,1982,glam punk,2,17,candy pop,3,34,quiet storm,3,25
8,8,1982,glam rock,2,17,country dawn,2,34,post-disco,3,25
9,9,1982,new romantic,2,17,rock,2,34,blues rock,2,25
10,10,1982,blues rock,1,17,new wave pop,2,34,piano rock,2,25
11,11,1982,cyberpunk,1,17,new wave,2,34,new romantic,2,25
12,12,1982,dance pop,1,17,new romantic,2,34,motown,2,25
13,13,1982,art rock,1,17,motown,2,34,jazz funk,2,25
14,14,1982,folk,1,17,heartland rock,2,34,bubblegum pop,2,25

# AUDIO FEATURES

# DANCEABILITY

In [28]:
top_10_dance_avg=final_1982_df.head(10)
top_10_dance_avg=top_10_dance_avg['danceability'].sum()/top_10_dance_avg['danceability'].count()*100
num_1_dance=final_1982_df['danceability']*100

dance_df=pd.DataFrame({'dance_avg':[final_1982_df['danceability'].sum()/final_1982_df['danceability'].count()*100],
                 'top10_dance_avg':[top_10_dance_avg],
                 'top_song_dance': [num_1_dance.iloc[0]]
                })
dance_df=dance_df.reset_index()
dance_df

   index  dance_avg  top10_dance_avg  top_song_dance
0      0  61.348485            71.29            82.9

# ENERGY

In [29]:
top_10_energy_avg=final_1982_df.head(10)
top_10_energy_avg=top_10_energy_avg['energy'].sum()/top_10_energy_avg['energy'].count()*100
num_1_energy=final_1982_df['energy']*100

energy_df=pd.DataFrame({'energy_avg':[final_1982_df['energy'].sum()/final_1982_df['energy'].count()*100],
                 'top10_energy_avg':[top_10_energy_avg],
                 'top_song_energy': [num_1_energy.iloc[0]]
                })
energy_df=energy_df.reset_index()
energy_df

   index  energy_avg  top10_energy_avg  top_song_energy
0      0   58.280808             58.67             73.7

# LIVENESS

In [30]:
top_10_live_avg=final_1982_df.head(10)
top_10_live_avg=top_10_live_avg['liveness'].sum()/top_10_live_avg['liveness'].count()*100
num_1_live=final_1982_df['liveness']*100

live_df=pd.DataFrame({'live_avg':[final_1982_df['liveness'].sum()/final_1982_df['liveness'].count()*100],
                 'top10_live_avg':[top_10_live_avg],
                 'top_song_live': [num_1_live.iloc[0]]
                })
live_df=live_df.reset_index()
live_df

   index   live_avg  top10_live_avg  top_song_live
0      0  19.211414          22.216           28.4

# DURATION

In [31]:
top_10_duration_avg=final_1982_df.head(10)
top_10_duration_avg=(top_10_duration_avg['duration_ms'].sum()/top_10_duration_avg['duration_ms'].count())/(60*1000)
num_1_duration=(final_1982_df['duration_ms'])/(60*1000)

duration_df=pd.DataFrame({'dur_avg':[(final_1982_df['duration_ms'].sum()/final_1982_df['duration_ms'].count())/(60*1000)],
                 'top10_dur_avg':[top_10_duration_avg],
                 'top_song_dur': [num_1_duration.iloc[0]]
                })
duration_df=duration_df.reset_index()
duration_df

   index   dur_avg  top10_dur_avg  top_song_dur
0      0  3.887549       3.871397      3.706667

# TEMPO

In [32]:
top_10_tempo_avg=final_1982_df.head(10)
top_10_tempo_avg=(top_10_tempo_avg['tempo'].sum()/top_10_tempo_avg['tempo'].count())
num_1_tempo=(final_1982_df['tempo'])

tempo_df=pd.DataFrame({'tempo_avg':[(final_1982_df['tempo'].sum()/final_1982_df['tempo'].count())],
                 'top10_tempo_avg':[top_10_tempo_avg],
                 'top_song_tempo': [num_1_tempo.iloc[0]]
                })
tempo_df=tempo_df.reset_index()
tempo_df

   index   tempo_avg  top10_tempo_avg  top_song_tempo
0      0  124.600758         114.1552         123.878

# VALENCE- Music Positiveness

In [33]:
top_10_valence_avg=final_1982_df.head(10)
top_10_valence_avg=(top_10_valence_avg['valence'].sum()/top_10_valence_avg['valence'].count()*100)
num_1_valence=(final_1982_df['valence'])*100

valence_df=pd.DataFrame({'valence_avg':[(final_1982_df['valence'].sum()/final_1982_df['valence'].count()*100)],
                 'top10_valence_avg':[top_10_valence_avg],
                 'top_song_valence': [num_1_valence.iloc[0]]
                })
valence_df=valence_df.reset_index()
valence_df

   index  valence_avg  top10_valence_avg  top_song_valence
0      0    65.373434              77.76              85.7

# ACOUSTICNESS

In [34]:
top_10_accoustic_avg=final_1982_df.head(10)
top_10_accoustic_avg=(top_10_accoustic_avg['acousticness'].sum()/top_10_accoustic_avg['acousticness'].count()*100)
num_1_accoustic=(final_1982_df['acousticness'])*100

accoustic_df=pd.DataFrame({'accoustic_avg':[(final_1982_df['acousticness'].sum()/final_1982_df['acousticness'].count()*100)],
                 'top10_accoustic_avg':[top_10_accoustic_avg],
                 'top_song_accoustic': [num_1_accoustic.iloc[0]]
                })
accoustic_df=accoustic_df.reset_index()
accoustic_df

   index  accoustic_avg  top10_accoustic_avg  top_song_accoustic
0      0      27.162631               20.964                13.0

# SPEECHINESS

In [35]:
top_10_speechiness_avg=final_1982_df.head(10)
top_10_speechiness_avg=(top_10_speechiness_avg['speechiness'].sum()/top_10_speechiness_avg['speechiness'].count()*100)
num_1_speechiness=(final_1982_df['speechiness'])*100

speechiness_df=pd.DataFrame({'speechiness_avg':[(final_1982_df['speechiness'].sum()/final_1982_df['speechiness'].count()*100)],
                 'top10_speechiness_avg':[top_10_accoustic_avg],
                 'top_song_speechiness': [num_1_accoustic.iloc[0]]
                })
speechiness_df=speechiness_df.reset_index()
speechiness_df

   index  speechiness_avg  top10_speechiness_avg  top_song_speechiness
0      0         3.826465                 20.964                  13.0

# KEY

In [36]:
key_trns=final_1982_df[['track_name','key','mode']]
key_trns.dtypes

track_name    object
key            int64
mode           int64
dtype: object

In [57]:
for index, row in key_trns.iterrows():
    key= int(row['key'])
    if key == 0 : 
        key_trns.loc[index,'key_a']= 'C'
    elif key ==1 : 
        key_trns.loc[index,'key_a']= 'C#'
    elif key ==2 : 
        key_trns.loc[index,'key_a']= 'D'
    elif key ==3 : 
        key_trns.loc[index,'key_a']= 'D#'
    elif key ==4 : 
        key_trns.loc[index,'key_a']= 'E'
    elif key ==5 : 
        key_trns.loc[index,'key_a']= 'F'
    elif key ==6 : 
        key_trns.loc[index,'key_a']= 'F#'
    elif key ==7 : 
        key_trns.loc[index,'key_a']= 'G'
    elif key ==8 : 
        key_trns.loc[index,'key_a']= 'G#'
    elif key ==9 : 
        key_trns.loc[index,'key_a']= 'A'
    elif key ==10 : 
        key_trns.loc[index,'key_a']= 'A#'
    elif key ==11 : 
        key_trns.loc[index,'key_a']= 'B'
    else:
        key_trns.loc[index,'key_a']= 'ERROR'        

for index, row in key_trns.iterrows():
    mode= int(row['mode'])
    if mode == 1 : 
        key_trns.loc[index,'M_m']= 'Major'
    elif mode ==0 : 
        key_trns.loc[index,'M_m']= 'minor'
    else:
        key_trns.loc[index,'M_m']= 'ERROR'

In [56]:
key_trns['alph_key']=key_trns['key_a']+key_trns['M_m']
key_trns_f=key_trns.drop(columns=['key', 'mode','key_a','M_m'])
key_trns_f['count']=1
key_trns_f.head()

C:\Users\vital\AppData\Local\Temp\ipykernel_34380\2755823312.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  key_trns['alph_key']=key_trns['key_a']+key_trns['M_m']

            track_name alph_key  count
0             Physical   Eminor      1
1     Eye of the Tiger   Cminor      1
2  I Love Rock 'N Roll   EMajor      1
3      Ebony And Ivory   EMajor      1
4           Centerfold   CMajor      1

In [58]:
pop_keys=key_trns_f.groupby(['alph_key'])['count'].count()
pop_keys= pd.DataFrame(pop_keys).reset_index().sort_values('count',ascending =False)
pop_keys= pop_keys.reset_index()
pop_keys= pop_keys.drop(columns=['index'])
pop_keys

   alph_key  count
0    EMajor     12
1    DMajor     11
2    CMajor     10
3    AMajor      8
4    GMajor      6
5   G#Major      6
6    FMajor      6
7   C#Major      5
8    Gminor      4
9    Aminor      4
10   BMajor      4
11   Dminor      4
12   Eminor      3
13  D#Major      3
14   Cminor      3
15   Bminor      3
16  C#minor      2
17  A#Major      2
18  A#minor      1
19  F#Major      1
20   Fminor      1

# FINAL SETS

# ENERGY-DANCE_TEMPO

In [60]:
energy_1982_df=dance_df.merge(tempo_df, how='left', on='index')
energy_1982_df=energy_1982_df.merge(energy_df, how='left', on='index')
energy_1982_df['year']=1982
energy_1982_df

,index,dance_avg,top10_dance_avg,top_song_dance,tempo_avg,top10_tempo_avg,top_song_tempo,energy_avg,top10_energy_avg,top_song_energy,year
0,0,61.348485,71.29,82.9,124.600758,114.1552,123.878,58.280808,58.67,73.7,1982

# VALENCE- ACCOUSTINESS- SPEECHINESS

In [61]:
tone_1982_df=valence_df.merge(accoustic_df, how='left', on='index')
tone_1982_df=tone_1982_df.merge(speechiness_df, how='left', on='index')
tone_1982_df['year']=1982
tone_1982_df

,index,valence_avg,top10_valence_avg,top_song_valence,accoustic_avg,top10_accoustic_avg,top_song_accoustic,speechiness_avg,top10_speechiness_avg,top_song_speechiness,year
0,0,65.373434,77.76,85.7,27.162631,20.964,13.0,3.826465,20.964,13.0,1982

# LIVENESS- DURATION

In [63]:
duration_1982_df=duration_df.merge(live_df, how='left', on='index')
duration_1982_df['year']=1982
duration_1982_df

,index,dur_avg,top10_dur_avg,top_song_dur,live_avg,top10_live_avg,top_song_live,year
0,0,3.887549,3.871397,3.706667,19.211414,22.216,28.4,1982

# MOST POPULAR KEYS

In [62]:
pop_keys

   alph_key  count
0    EMajor     12
1    DMajor     11
2    CMajor     10
3    AMajor      8
4    GMajor      6
5   G#Major      6
6    FMajor      6
7   C#Major      5
8    Gminor      4
9    Aminor      4
10   BMajor      4
11   Dminor      4
12   Eminor      3
13  D#Major      3
14   Cminor      3
15   Bminor      3
16  C#minor      2
17  A#Major      2
18  A#minor      1
19  F#Major      1
20   Fminor      1

# MOST POPULAR GENRES

In [64]:
genre_1982_df

,index,year,primary_genre,p_gen_count,pg_count,sub_genre_1,sg1_count,s1_count,sub_genre_2,sg2_count,s2_count
0,0,1982,album rock,45,17,classic rock,20,34,classic rock,15,25
1,1,1982,adult standards,16,17,art rock,9,34,country rock,15,25
2,2,1982,disco,10,17,disco,6,34,mellow gold,10,25
3,3,1982,mellow gold,5,17,mellow gold,5,34,hard rock,5,25
4,4,1982,classic country pop,4,17,funk,5,34,new wave pop,4,25
5,5,1982,country,2,17,soft rock,4,34,girl group,4,25
6,6,1982,funk,2,17,bubblegum pop,3,34,soft rock,3,25
7,7,1982,glam punk,2,17,candy pop,3,34,quiet storm,3,25
8,8,1982,glam rock,2,17,country dawn,2,34,post-disco,3,25
9,9,1982,new romantic,2,17,rock,2,34,blues rock,2,25
10,10,1982,blues rock,1,17,new wave pop,2,34,piano rock,2,25
11,11,1982,cyberpunk,1,17,new wave,2,34,new romantic,2,25
12,12,1982,dance pop,1,17,new romantic,2,34,motown,2,25
13,13,1982,art rock,1,17,motown,2,34,jazz funk,2,25
14,14,1982,folk,1,17,heartland rock,2,34,bubblegum pop,2,25

# TIME SIGNATURE PERCENTAGES

In [67]:
percent_time_sig_1982

96.96969696969697

# FINAL FULL DATAFRAME

In [68]:
final_1982_df

,index,artist_name,year,track_name,primary_genre,sub_genre_1,sub_genre_2,danceability,energy,key,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,track_uri,duration_ms,time_signature
0,0,Olivia Newton-John,1982,Physical,adult standards,australian dance,bubblegum pop,0.829,0.737,4,...,0,0.0441,0.1300,0.000063,0.2840,0.857,123.878,3FuL7jThtUAjneBm6puQNk,222400,4
1,1,Survivor,1982,Eye of the Tiger,album rock,hard rock,rock,0.815,0.438,0,...,0,0.0346,0.2160,0.000466,0.0787,0.552,108.965,2HHtWyy5CgaQbC7XSoOb0e,243773,4
2,2,Joan Jett & the Blackhearts,1982,I Love Rock 'N Roll,glam punk,rock,None,0.535,0.716,4,...,1,0.0431,0.3260,0.000000,0.6590,0.901,94.379,2Cdvbe2G4hZsnhNMKyGrie,175173,4
3,3,Paul McCartney,1982,Ebony And Ivory,album rock,beatlesque,classic rock,0.639,0.458,4,...,1,0.0343,0.1520,0.000000,0.1680,0.805,80.692,1h3bcnnIm72UnemGIfm0iZ,220773,4
4,4,The J. Geils Band,1982,Centerfold,album rock,art rock,blues rock,0.653,0.677,0,...,1,0.0396,0.2490,0.000000,0.4030,0.888,114.370,1ynmMEK1fkyiZ6Z6F3ThEt,216533,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,94,Stevie Wonder,1982,Do I Do - Single Version,funk,motown,quiet storm,0.713,0.862,11,...,1,0.0519,0.0948,0.000012,0.3300,0.894,113.268,5OUfoG39D9qGF6FcvX3Yp7,301800,4
95,95,Loverboy,1982,Working for the Weekend,album rock,classic canadian rock,classic rock,0.515,0.766,7,...,1,0.0343,0.0249,0.001030,0.4550,0.774,146.911,35k31HZI4z9PbBOioaI4dZ,221000,4
96,96,Christopher Cross,1982,Arthur's Theme (Best That You Can Do),adult standards,album rock,disco,0.526,0.515,9,...,1,0.0389,0.1690,0.000816,0.1810,0.518,136.543,5fnOrhQ4KgT5irGCjIccGH,234493,4
97,97,Kenny Rogers,1982,Through The Years - Single Version,adult standards,classic country pop,country,0.554,0.487,0,...,1,0.0264,0.3480,0.000001,0.2130,0.258,131.127,5TSSjhWoGjWJfkfa6lziFJ,285027,4
98,98,Stevie Nicks,1982,Edge of Seventeen - 2016 Remaster,album rock,heartland rock,mellow gold,0.591,0.804,0,...,1,0.0454,0.3270,0.000006,0.0818,0.658,111.457,7L3b6iaVhDVjfo52Hbvh9Z,329413,4